name: cloud_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  http: ^1.3.0
  json_annotation: ^4.9.0
  result_dart: ^2.1.0
  shared_preferences: ^2.5.3
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  lints: ^5.0.0
  test: ^1.24.0
